routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MaterielController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\FournisseurController;
use App\Http\Controllers\AccessoireController;
use App\Http\Controllers\LogicielController;
use App\Http\Controllers\FactureController;
use App\Http\Controllers\MaintenanceController;
use App\Http\Controllers\MachineController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->name('login');

Auth::routes();

Route::get('admin/home', [HomeController::class, 'adminHome'])->name('admin.home')->middleware('is_admin');

Route::get('/home', [HomeController::class, 'index'])->name('home')->middleware('auth');

Route::get('/userProfil', function (){
    return view('userProfil');
})->name('userProfil')->middleware('auth');;


Route::resource('machines', MachineController::class)->middleware('is_admin');

Route::resource('users', UserController::class)->middleware('is_admin');

Route::resource('maintenances', MaintenanceController::class)->middleware('auth');
Route::get('admin/index', [MaintenanceController::class, 'indexadmin'])->name('maintenances.indexadmin')->middleware('is_admin');

Route::resource('logiciels', LogicielController::class)->middleware('auth');

Route::resource('factures', FactureController::class)->middleware('auth');

Route::resource('fournisseurs', FournisseurController::class)->middleware('auth');;

Route::resource('accessoires', AccessoireController::class)->middleware('auth');

Route::resource('materiels', MaterielController::class)->middleware('auth');

app/Models/Logiciel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Logiciel extends Model
{
    use HasFactory, Notifiable;
    protected $fillable = [
      'log_nom',
      'log_serie',
      'log_marque',
        'log_license',
      'log_prixachat',
      'log_dateachat',
      'log_garantie',
      'for_id',
        'fac_id',
    ];

    public function facture(){
        return $this->belongsTo(Facture::class, 'fac_id');
    }

    public function fournisseur(){
        return $this->belongsTo(Fournisseur::class, 'for_id');
    }
}

app/Http/Controllers/LogicielController.php
<?php

namespace App\Http\Controllers;

use App\Models\Facture;
use App\Models\Logiciel;
use Illuminate\Http\Request;
use App\Models\Fournisseur;

class LogicielController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */

    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $logiciels = Logiciel::where([
            ['log_serie', "!=", NULL],
            [function($query) use ($request){
                if (($term = $request->term)){
                    $query->orWhere('log_serie', 'LIKE', '%', $term, '%')->get();
                }
            }]
        ])->orderBy("id", "desc")->paginate(5);
        //$materiels = Materiel::latest()->paginate(5);
        return view('logiciels.index', compact('logiciels'))->with('i', (\request()->input('page', 1)-1)*5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $fournisseurs = Fournisseur::all();
        $factures = Facture::all();
        return view('logiciels.create', compact('fournisseurs', 'factures'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'log_nom'=>'required',
            'log_serie'=>'required',
            'log_marque'=>'required',
            'log_license'=>'required',
            'log_prixachat'=>'required',
            'log_dateachat'=>'required',
            'log_garantie'=>'required',
            'for_id'=>'required',
            'fac_id'=>'required',
        ]);
        Logiciel::create($request->all());
        return redirect()->route('logiciels.index',)->with('success', 'Logiciel ajoute avec succes');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Logiciel  $logiciel
     * @return \Illuminate\Http\Response
     */
    public function show(Logiciel $logiciel)
    {
        $fournisseur = Fournisseur::findORFail($logiciel->for_id);
        $facture = Facture::findOrFail($logiciel->fac_id);
        return view('logiciels.show',compact('logiciel', 'fournisseur','facture'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Logiciel  $logiciel
     * @return \Illuminate\Http\Response
     */
    public function edit(Logiciel $logiciel)
    {
        $fournisseurs = Fournisseur::all();
        $factures = Facture::all();
        return view('logiciels.edit',compact('logiciel', 'fournisseurs','factures'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Logiciel  $logiciel
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Logiciel $logiciel)
    {
        $request->validate([
            'log_nom'=>'required',
            'log_serie'=>'required',
            'log_marque'=>'required',
            'log_prixachat'=>'required',
            'log_dateachat'=>'required',
            'log_garantie'=>'required',
            'for_id'=>'required',
            'fac_id'=>'required',
        ]);
        $logiciel->update($request->all());
        return redirect()->route('logiciels.index')->with('success', 'Logiciel met a jour avec succes');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Logiciel  $logiciel
     * @return \Illuminate\Http\Response
     */
    public function destroy(Logiciel $logiciel)
    {
        $logiciel->delete();
        return redirect()->route('logiciels.index')->with('success', 'Logiciel supprime avec succes');
    }
}

resources/views/logiciels/create.blade.php
@extends('layouts.userApp')

@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="card">
                <div class="content">
                    <div class="row">
                        <div class="col-md-6">
                            <a class="btn-neutral" style="color: #000000;" href="{{ route('factures.create') }}"><i class="fa fa-link"></i>{{ __('Ajouter facture. Si le logiciel appartient a une nouvelle facture.') }}</a>
                        </div>
                        <div class="col-md-6">
                            <a class="btn-neutral" style="color: #000000;" href="{{ route('fournisseurs.create') }}"><i class="fa fa-link"></i>{{ __('Ajouter fournisseur. Si le logiciel fournit par un nouveau fournisseur.') }}</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8 col-md-offset-2">
            <div class="card">
                <div class="header">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert">
                                <span aria-hidden="true">&times;</span><span class="sr-only"><i class="pe-7s-close-circle"></i></span>
                            </button>
                            <strong>Whoops!</strong> Il y a eu des problemes avec votre entree.<br><br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <a class="btn btn-info btn-fill" href="{{ route('logiciels.index') }}">Retour</a>
                </div>
                <div class="content">
                    <form action="{{ route('logiciels.store') }}" method="post">
                        @csrf
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label for="mat_serie">{{ __('Serie') }}</label>
                                    <input type="text" class="form-control" name="log_serie">
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label for="mat_nom">{{ __('Nom') }}</label>
                                    <input type="text" class="form-control" name="log_nom">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="mat_model">{{ __('Marque') }}</label>
                                    <input type="text" class="form-control" name="log_marque">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="log_license">{{ __('License') }}</label>
                                    <input type="text" class="form-control" name="log_license">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="for_id">{{ __('Fournisseur') }}</label>
                                    <select name="for_id" class="form-control">
                                        @foreach($fournisseurs as $fournisseur)
                                            <option value="{{ $fournisseur->id }}">{{ $fournisseur->for_nom }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="fac_id">{{ __('Facture') }}</label>
                                    <select name="fac_id" class="form-control">
                                        @foreach($factures as $facture)
                                            <option value="{{ $facture->id }}">{{ $facture->id }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="mat_prixachat">{{ __('Prix Achat') }}</label>
                                    <input type="number" step="0.01" name="log_prixachat" class="form-control">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="mat_garantie">{{ __('Garantie') }}</label>
                                    <input type="text" class="form-control" name="log_garantie">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="mat_dateachat">{{ __('Date Achat') }}</label>
                                    <input type="Date" class="form-control" name="log_dateachat">
                                </div>
                            </div>
                        </div>
                        <input type="submit" class="btn btn-info btn-fill pull-right" value="{{ __('Ajouter') }}">
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/logiciels/edit.blade.php
@extends('layouts.userApp')

@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="card">
                <div class="header">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert">
                                <span aria-hidden="true">&times;</span><span class="sr-only"><i class="pe-7s-close-circle"></i></span>
                            </button>
                            <strong>Whoops!</strong> Il y a eu des problemes avec votre entree.<br><br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <a class="btn btn-info btn-fill" href="{{ route('logiciels.index') }}">Retour</a>
                </div>
                <div class="content">
                    <form action="{{ route('logiciels.update', $logiciel->id) }}" method="post">
                        @csrf
                        @method('PUT')
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label for="mat_serie">{{ __('Serie') }}</label>
                                    <input type="text" class="form-control" name="log_serie" value="{{ __($logiciel->log_serie) }}">
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label for="mat_nom">{{ __('Nom') }}</label>
                                    <input type="text" class="form-control" name="log_nom" value="{{ __($logiciel->log_nom) }}">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="mat_model">{{ __('Marque') }}</label>
                                    <input type="text" class="form-control" name="log_marque" value="{{ __($logiciel->log_marque) }}">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="log_license">{{ __('License') }}</label>
                                    <input type="text" class="form-control" name="log_license" value="{{ __($logiciel->log_license) }}">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="for_id">{{ __('Fournisseur') }}</label>
                                    <select name="for_id" class="form-control">
                                        @foreach($fournisseurs as $fournisseur)
                                            <option value="{{ $fournisseur->id }}">{{ $fournisseur->for_nom }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="fac_id">{{ __('Facture') }}</label>
                                    <select name="fac_id" class="form-control">
                                        @foreach($factures as $facture)
                                            <option value="{{ $facture->id }}">{{ $facture->id }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="mat_prixachat">{{ __('Prix Achat') }}</label>
                                    <input type="number" step="0.01" name="log_prixachat" class="form-control" value="{{ __($logiciel->log_prixachat) }}">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="mat_garantie">{{ __('Garantie') }}</label>
                                    <input type="text" class="form-control" name="log_garantie" value="{{ __($logiciel->log_garantie) }}">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="mat_dateachat">{{ __('Date Achat') }}</label>
                                    <input type="Date" class="form-control" name="log_dateachat" value="{{ __($logiciel->log_dateachat) }}">
                                </div>
                            </div>
                        </div>
                        <input type="submit" class="btn btn-info btn-fill pull-right" value="{{ __('Modifier') }}">
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/logiciels/index.blade.php
@extends('layouts.userApp')

@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="card">
                <div class="header">
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <button type="button" class="close" data-dismiss="alert">
                                <span aria-hidden="true">&times;</span><span class="sr-only"><i class="pe-7s-close-circle"></i></span>
                            </button>
                            <p>{{ $message }}</p>
                        </div>
                    @endif
                    <a class="btn btn-info btn-fill" href="{{ route('logiciels.create') }}"><i class="fa fa-plus-circle"></i>{{__('Ajouter un nouveau logiciel')}}</a>
                    <form class="form-inline my-2 my-lg-0 pull-right" action="{{ route('logiciels.index') }}" method="get" role="search">
                        <input class="form-control mr-sm-2" type="search" name="term" placeholder="{{ __('Chercher par le N° de serie') }}" aria-label="Search">
                        <button class="btn btn-info btn-fill my-2 my-sm-0" type="submit"><i class="fa fa-search"></i></button>
                    </form>
                </div>
                <div class="content table-responsive table-full-width center-block">
                    <table class="table table-hover table-striped">
                        <thead>
                        <th>Serie</th>
                        <th>Name</th>
                        <th>Date Achat</th>
                        <th>Plus</th>
                        <th>Modifier</th>
                        <th>Supprimer</th>
                        </thead>
                        <tbody>
                        @foreach ($logiciels as $logiciel)
                            <tr>
                                <td>{{ $logiciel->log_serie }}</td>
                                <td>{{ $logiciel->log_nom }}</td>
                                <td>{{ $logiciel->log_dateachat }}</td>
                                <td> <a class="btn" href="{{ route('logiciels.show',$logiciel->id) }}"><i class="fa fa-eye" style="color: #000000;"></i></a></td>
                                <td> <a class="btn" href="{{ route('logiciels.edit',$logiciel->id) }}"><i class="fa fa-edit" style="color: #000000;"></i></a></td>
                                <td>
                                    <form action="{{ route('logiciels.destroy',$logiciel->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn"><i class="fa fa-trash" style="color: #000000;"></i></button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="d-flex justify-content-center">
                {!! $logiciels->links('pagination::bootstrap-4') !!}
            </div>
        </div>
    </div>
@endsection

resources/views/logiciels/show.blade.php
@extends('layouts.userApp')

@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="card">
                <div class="header">
                    <a class="btn btn-info btn-fill" href="{{ route('logiciels.index') }}">Retour</a>
                    <a class="btn btn-info btn-fill" href="{{ route('logiciels.edit', $logiciel->id) }}">Modifer</a>
                </div>
                <div class="content">
                    <form>
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label>{{ __('Serie') }}</label>
                                    <input type="email" class="form-control" value="{{ $logiciel->log_serie }}" readonly>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label>{{ __('Nom') }}</label>
                                    <input type="text" class="form-control" value="{{ $logiciel->log_nom }}" readonly>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>{{ __('Marque') }}</label>
                                    <input type="text" class="form-control" value="{{ $logiciel->log_marque }}" readonly>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="log_license">{{ __('License') }}</label>
                                    <input type="text" class="form-control" name="log_license" value="{{ $logiciel->log_license }}" readonly>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>{{ __('Fournisseur') }}</label>
                                    <input type="text" class="form-control" value="{{ $fournisseur->for_nom }}" readonly>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="fac_id">{{ __('N° Facture') }}</label>
                                    <input class="form-control" value="{{ $logiciel->fac_id }}" readonly>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>{{ __('Prix Achat') }}</label>
                                    <input type="number" class="form-control" value="{{ $logiciel->log_prixachat }}" readonly>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>{{ __('Garantie') }}</label>
                                    <input type="text" class="form-control" value="{{ $logiciel->log_garantie }}" readonly>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>{{ __('Date Achat') }}</label>
                                    <input type="Date" class="form-control" value="{{ $logiciel->log_dateachat }}" readonly>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>{{ __('La Date D\'ajout') }}</label>
                                    <input type="" class="form-control" value="{{ $logiciel->created_at }}" readonly>
                                </div>
                            </div>
                            <div class="col-md-6">

                                <div class="form-group">
                                    <label>{{ __('Dernier mis a jour') }}</label>
                                    @if($logiciel->updated_at != $logiciel->created_at)
                                    <input type="" class="form-control" value="{{ $logiciel->updated_at }}" readonly>
                                    @else
                                        <input type="" class="form-control" value="{{ __('Aucune Modification') }}" readonly>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection