routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MaterielController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\FournisseurController;
use App\Http\Controllers\AccessoireController;
use App\Http\Controllers\LogicielController;
use App\Http\Controllers\FactureController;
use App\Http\Controllers\MaintenanceController;
use App\Http\Controllers\MachineController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->name('login');

Auth::routes();

Route::get('admin/home', [HomeController::class, 'adminHome'])->name('admin.home')->middleware('is_admin');

Route::get('/home', [HomeController::class, 'index'])->name('home')->middleware('auth');

Route::get('/userProfil', function (){
    return view('userProfil');
})->name('userProfil')->middleware('auth');;


Route::resource('machines', MachineController::class)->middleware('is_admin');

Route::resource('users', UserController::class)->middleware('is_admin');

Route::resource('maintenances', MaintenanceController::class)->middleware('auth');
Route::get('admin/index', [MaintenanceController::class, 'indexadmin'])->name('maintenances.indexadmin')->middleware('is_admin');

Route::resource('logiciels', LogicielController::class)->middleware('auth');

Route::resource('factures', FactureController::class)->middleware('auth');

Route::resource('fournisseurs', FournisseurController::class)->middleware('auth');;

Route::resource('accessoires', AccessoireController::class)->middleware('auth');

Route::resource('materiels', MaterielController::class)->middleware('auth');

app/Models/Facture.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Facture extends Model
{
    use HasFactory, Notifiable;
    protected $fillable = [
        'fact_date',
        'prixtotal',
        'for_id',
    ];

    public function materiels(){
        return $this->hasMany(Materiel::class);
    }
    public function logiciels(){
        return$this->hasMany(Logiciel::class);
    }
    public function fournisseur(){
        return $this->belongsTo(Fournisseur::class, 'for_id');
    }
}

app/Http/Controllers/FactureController.php
<?php

namespace App\Http\Controllers;

use App\Models\Facture;
use Illuminate\Http\Request;
use App\Models\Fournisseur;
use App\Models\Materiel;
use App\Models\Logiciel;

class FactureController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $factures = Facture::latest()->paginate(6);
        foreach($factures as $facture){
            $fournisseur=Fournisseur::where('id',$facture->for_id)->get();
            $fournisseurs[] = $fournisseur;
        }
        return view('factures.index', compact('factures','fournisseurs'))->with('i',(\request()->input('page',1)-1)*6);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $fournisseurs = Fournisseur::all();
        return view('factures.create',compact('fournisseurs'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'fact_date' => 'required',
            'prixtotal' => 'required',
            'for_id' => 'required',
        ]);
        Facture::create($request->all());
        return redirect()->route('factures.index')->with('success', 'Facture ajouter avec succes');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Facture  $facture
     * @return \Illuminate\Http\Response
     */
    public function show(Facture $facture)
    {
        $materiels = Materiel::where('fac_id', $facture->id)->get();
        $logiciels = Logiciel::where('fac_id', $facture->id)->get();
        $fournisseur = Fournisseur::findOrFail($facture->for_id);
        return view('factures.show', compact('facture', 'materiels','logiciels','fournisseur'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Facture  $facture
     * @return \Illuminate\Http\Response
     */
    public function edit(Facture $facture)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Facture  $facture
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Facture $facture)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Facture  $facture
     * @return \Illuminate\Http\Response
     */
    public function destroy(Facture $facture)
    {
        //
    }
}

resources/views/factures/create.blade.php
@extends('layouts.userApp')

@section('content')
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="card">
                <div class="header">
                    <a class="btn btn-info btn-fill" href="{{ route('factures.index') }}">retour</a>
                </div>
                <div class="content">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert">
                                <span aria-hidden="true">&times;</span><span class="sr-only"><i class="pe-7s-close-circle"></i></span>
                            </button>
                            <strong>Whoops!</strong> Il y a eu quelques problèmes avec votre entrée.<br><br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form action="{{ route('factures.store') }}" method="post">
                        @csrf
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="fact_date">{{ __('Date de facture') }}</label>
                                    <input type="Date" class="form-control" name="fact_date">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="for_id">{{ __('Fournisseur') }}</label>
                                    <select name="for_id" class="form-control">
                                        @foreach($fournisseurs as $fournisseur)
                                            <option value="{{ $fournisseur->id }}">{{ $fournisseur->for_nom }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="prix_achat">{{ __('Prix Total') }}</label>
                                    <input type="number" step="0.01" class="form-control" name="prixtotal">
                                </div>
                            </div>
                        </div>

                        <input type="submit" class="btn btn-info btn-fill pull-right" value="{{ __('Ajouter') }}">
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/factures/index.blade.php
@extends('layouts.userApp')

@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="card">
                <div class="header">
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <button type="button" class="close" data-dismiss="alert">
                                <span aria-hidden="true">&times;</span><span class="sr-only"><i class="pe-7s-close-circle"></i></span>
                            </button>
                            <p>{{ $message }}</p>
                        </div>
                    @endif
                    <a class="btn btn-info btn-fill" href="{{ route('factures.create') }}"><i class="fa fa-plus-circle"></i>{{__('Ajouter une nouvelle facture')}}</a>
                </div>
                <div class="content table-responsive table-full-width center-block">
                    <table class="table table-hover table-striped">
                        <thead>
                        <th>N° Facture</th>
                        <th>date de facture</th>
                        <th>prix Total</th>
                        <th>Fournisseur</th>
                        <th>Plus</th>
                        <th>Modifier</th>
                        <th>Supprimer</th>
                        </thead>
                        <tbody>
                        @foreach ($factures as $facture)
                            <tr>
                                <td>{{ $facture->id }}</td>
                                <td>{{ $facture->fact_date }}</td>
                                <td>{{ $facture->prixtotal }}</td>
                                @foreach($fournisseurs as $fournisseur)
                                    @if($facture->for_id == $fournisseur[0]->id)
                                        <td><a href="{{ route('fournisseurs.show',$fournisseur[0]->id) }}">{{ $fournisseur[0]->for_nom }}</a></td>
                                    @endif
                                @endforeach
                                <td> <a class="btn" href="{{ route('factures.show',$facture->id) }}"><i class="fa fa-eye" style="color: #000000;"></i></a></td>
                                <td> <a class="btn" href="{{ route('factures.edit',$facture->id) }}"><i class="fa fa-edit" style="color: #000000;"></i></a></td>
                                <td>
                                    <form action="{{ route('factures.destroy',$facture->id) }}" method="POST">

                                        @csrf
                                        @method('DELETE')

                                        <button type="submit" class="btn"><i class="fa fa-trash" style="color: #000000;"></i></button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="d-flex justify-content-center">
                {!! $factures->links('pagination::bootstrap-4') !!}
            </div>
        </div>
    </div>
@endsection

resources/views/factures/show.blade.php
@extends('layouts.userApp')

@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="card">
                <div class="header">
                    <a class="btn btn-info btn-fill" href="{{ route('factures.index') }}">Retour</a>
                <div class="content">
                    <form>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>{{ __('Date de Facture') }}</label>
                                    <input type="email" class="form-control" value="{{ $facture->id }}" readonly>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>{{ __('Date de Facture') }}</label>
                                    <input type="email" class="form-control" value="{{ $facture->fact_date }}" readonly>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>{{ __('Fournisseure') }}</label>
                                    <input type="text" class="form-control" value="{{ $fournisseur->for_nom }}" readonly>
                                </div>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
        @if(Auth::user()->is_admin)
            <div class="row">
                <div class="col-md-10 col-md-offset-1">
                    <div class="row center-block">
                        <div class="col-md-6">
                            <div class="card">
                                <div class="header">
                                    <button class="btn btn-info btn-fill center-block">{{ __('Liste des materiels Dans la facture') }}</button>
                                </div>
                                <br/>
                                <div class="content table-responsive table-full-width">
                                    <table class="table table-hover table-striped">
                                        <thead>
                                        <th>{{__('Serie')}}</th>
                                        <th>{{__('Name')}}</th>
                                        <th>{{__('Plus')}}</th>
                                        </thead>
                                        <tbody>
                                        @foreach ($materiels as $materiel)
                                            <tr>
                                                <td>{{ $materiel->mat_serie }}</td>
                                                <td>{{ $materiel->mat_nom }}</td>
                                                <td> <a class="btn" href="{{ route('materiels.show',$materiel->id) }}"><i class="fa fa-eye" style="color: #000000;"></i></a></td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="card">
                                <div class="header">
                                    <button class="btn btn-info btn-fill center-block">{{ __('Liste des logiciels dans la facture ')}}</button>
                                </div>
                                <br/>
                                <div class="content table-responsive table-full-width">
                                    <table class="table table-hover table-striped">
                                        <thead class="thead-dark">
                                        <th>{{__('Serie')}}</th>
                                        <th>{{__('Name')}}</th>
                                        <th>{{__('Plus')}}</th>
                                        </thead>
                                        <tbody>
                                        @foreach ($logiciels as $logiciel)
                                            <tr>
                                                <td>{{ $logiciel->log_serie }}</td>
                                                <td>{{ $logiciel->log_nom }}</td>
                                                <td> <a class="btn" href="{{ route('logiciels.show',$logiciel->id) }}"><i class="fa fa-eye" style="color: #000000;"></i></a></td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    @endif
@endsection