routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MaterielController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\FournisseurController;
use App\Http\Controllers\AccessoireController;
use App\Http\Controllers\LogicielController;
use App\Http\Controllers\FactureController;
use App\Http\Controllers\MaintenanceController;
use App\Http\Controllers\MachineController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->name('login');

Auth::routes();

Route::get('admin/home', [HomeController::class, 'adminHome'])->name('admin.home')->middleware('is_admin');

Route::get('/home', [HomeController::class, 'index'])->name('home')->middleware('auth');

Route::get('/userProfil', function (){
    return view('userProfil');
})->name('userProfil')->middleware('auth');;


Route::resource('machines', MachineController::class)->middleware('is_admin');

Route::resource('users', UserController::class)->middleware('is_admin');

Route::resource('maintenances', MaintenanceController::class)->middleware('auth');
Route::get('admin/index', [MaintenanceController::class, 'indexadmin'])->name('maintenances.indexadmin')->middleware('is_admin');

Route::resource('logiciels', LogicielController::class)->middleware('auth');

Route::resource('factures', FactureController::class)->middleware('auth');

Route::resource('fournisseurs', FournisseurController::class)->middleware('auth');;

Route::resource('accessoires', AccessoireController::class)->middleware('auth');

Route::resource('materiels', MaterielController::class)->middleware('auth');

app/Models/Fournisseur.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Fournisseur extends Model
{
    use HasFactory, Notifiable;

    protected $fournisseur;

    protected $fillable =[
        'for_nom',
        'for_adress',
        'for_zip',
        'for_ville',
        'for_telephone',
        'for_email',
        'for_fax',
        'rib',
    ];

    public function materiels(){
        return $this->hasMany(Materiel::class);
    }
    public function logiciels(){
        return$this->hasMany(Logiciel::class);
    }
}

app/Http/Controllers/FournisseurController.php
<?php

namespace App\Http\Controllers;

use App\Models\Fournisseur;
use App\Models\Logiciel;
use App\Models\Materiel;
use Illuminate\Http\Request;

class FournisseurController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
       $fournisseurs = Fournisseur::where([
            ['for_nom', "!=", NULL],
            [function($query) use ($request){
                if (($term = $request->term)){
                    $query->orWhere('for_nom', 'LIKE', '%', $term, '%')->get();
                }
            }]
        ])->orderBy("id", "desc")->paginate(6);
        //$fournisseurs = Fournisseur::latest()->paginate(4);
        return view('fournisseurs.index', compact('fournisseurs'))->with('i', (\request()->input('page',1)-1)*6);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('fournisseurs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'for_nom'=>'required',
            'for_email' => ['required', 'string', 'email', 'max:255', 'unique:fournisseurs'],
            'for_telephone'=>'required',
            'for_fax'=>'required',
            'for_ville'=>'required',
            'for_zip'=>'required',
            'for_adress'=>'required',
            'rib' => 'required',
        ]);
        Fournisseur::create($request->all());
        return redirect()->route('fournisseurs.index')->with('success', 'Fournisseur ajouter avec succes');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Fournisseur  $fournisseur
     * @return \Illuminate\Http\Response
     */
    public function show(Fournisseur $fournisseur)
    {
        $materiels = Materiel::where('for_id',$fournisseur->id)->get();
        $logiciels = Logiciel::where('for_id',$fournisseur->id)->get();
        return view('fournisseurs.show', compact('fournisseur', 'materiels','logiciels'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Fournisseur  $fournisseur
     * @return \Illuminate\Http\Response
     */
    public function edit(Fournisseur $fournisseur)
    {
        return view('fournisseurs.edit', compact('fournisseur'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Fournisseur  $fournisseur
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Fournisseur $fournisseur)
    {
        $request->validate([
            'for_nom'=>'required',
            'for_email'=>'required',
            'for_telephone'=>'required',
            'for_fax'=>'required',
            'for_ville'=>'required',
            'for_zip'=>'required',
            'for_adress'=>'required',
            'rib' => 'required',
        ]);
        $fournisseur->update($request->all());

        return redirect()->route('fournisseurs.index')->with('success', 'Fournisseur mis a jour avec succes');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Fournisseur  $fournisseur
     * @return \Illuminate\Http\Response
     */
    public function destroy(Fournisseur $fournisseur)
    {
        $fournisseur->delete();

        return redirect()->route('fournisseurs.index')->with('success', 'Fournisseur supprime avec succes');
    }
}

resources/views/fournisseurs/create.blade.php
@extends('layouts.userApp')

@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="card">
                <div class="header">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert">
                                <span aria-hidden="true">&times;</span><span class="sr-only"><i class="pe-7s-close-circle"></i></span>
                            </button>
                            <strong>Whoops!</strong> Il y a eu des problèmes avec votre entree.<br><br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <a class="btn btn-info btn-fill" href="{{ route('fournisseurs.index') }}">Retour</a>
                </div>
                <div class="content">
                    <form action="{{ route('fournisseurs.store') }}" method="POST">
                        @csrf
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>{{ __('Nom Complet') }}</label>
                                    <input type="text" name="for_nom" class="form-control">
                                </div>
                            </div>
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label>{{ __('E-mail') }}</label>
                                    <input type="email" name="for_email" class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>{{ __('RIB') }}</label>
                                    <input type="text" class="form-control" name="rib">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>{{ __('N° Telephone') }}</label>
                                    <input class="form-control" type="tel" name="for_telephone">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>{{ __('Fax') }}</label>
                                    <input class="form-control" type="tel" name="for_fax">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <div class="form-group">
                                    <label>{{ __('Ville') }}</label>
                                    <input class="form-control" type="text" name="for_ville">
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="form-group">
                                    <label>{{ __('Code Postale') }}</label>
                                    <input class="form-control" name="for_zip" type="text">
                                </div>
                            </div>
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label>{{ __('Adresse') }}</label>
                                    <input type="" class="form-control" type="text" name="for_adress">
                                </div>
                            </div>
                        </div>
                        <input type="submit" class="btn btn-info btn-fill pull-right" value="{{ __('Ajouter') }}">
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/fournisseurs/edit.blade.php
@extends('layouts.userApp')

@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="card">
                <div class="header">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <strong>Whoops!</strong> Il y a eu des problemes avec votre entree.<br><br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <a class="btn btn-info btn-fill" href="{{ route('fournisseurs.index') }}">Retour</a>
                </div>
                <div class="content">
                    <form action="{{ route('fournisseurs.update', $fournisseur->id) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>{{ __('Nom Complet') }}</label>
                                    <input type="text" name="for_nom" class="form-control" value="{{ $fournisseur->for_nom }}">
                                </div>
                            </div>
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label>{{ __('E-mail') }}</label>
                                    <input type="email" name="for_email" class="form-control" value="{{ $fournisseur->for_email }}">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>{{ __('RIB') }}</label>
                                    <input type="text" class="form-control" name="rib" value="{{ $fournisseur->rib }}">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>{{ __('N° Telephone') }}</label>
                                    <input class="form-control" type="tel" name="for_telephone" value="{{ $fournisseur->for_telephone }}">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>{{ __('Fax') }}</label>
                                    <input class="form-control" type="tel" name="for_fax" value="{{ $fournisseur->for_fax }}">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <div class="form-group">
                                    <label>{{ __('Ville') }}</label>
                                    <input class="form-control" type="text" name="for_ville" value="{{ $fournisseur->for_ville }}">
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="form-group">
                                    <label>{{ __('Code Postale') }}</label>
                                    <input class="form-control" name="for_zip" type="text" value="{{ $fournisseur->for_zip }}">
                                </div>
                            </div>
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label>{{ __('Adresse') }}</label>
                                    <input type="" class="form-control" type="text" name="for_adress" value="{{ $fournisseur->for_adress }}">
                                </div>
                            </div>
                        </div>
                        <input type="submit" class="btn btn-info btn-fill pull-right" value="{{ __('Modifier') }}">
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/fournisseurs/index.blade.php
@extends('layouts.userApp')

@section('content')
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="card">
                <div class="header">
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <button type="button" class="close" data-dismiss="alert">
                                <span aria-hidden="true">&times;</span><span class="sr-only"><i class="pe-7s-close-circle"></i></span>
                            </button>
                            <p>{{ $message }}</p>
                        </div>
                    @endif
                        <a class="btn btn-info btn-fill" href="{{ route('fournisseurs.create') }}"><i class="fa fa-plus-circle"></i>{{__('Ajouter un nouveau fournisseur')}}</a>
                        <form class="form-inline my-2 my-lg-0 pull-right" action="{{ route('fournisseurs.index') }}" method="get" role="search">
                            <input class="form-control mr-sm-2" type="search" name="term" placeholder="{{ __('Chercher par le nom') }}" aria-label="Search">
                            <button class="btn btn-info btn-fill my-2 my-sm-0" type="submit"><i class="fa fa-search"></i></button>
                        </form>
                </div>
                <div class="content table-responsive table-full-width">
                    <table class="table table-hover table-striped">
                        <thead>
                        <th>Nom Complet</th>
                        <th>Ville</th>
                        <th>Email</th>
                        <th>N° Telephone</th>
                        <th>Plus</th>
                        <th>Modifier</th>
                        <th>Supprimer</th>
                        </thead>
                        <tbody>
                        @foreach ($fournisseurs as $fournisseur)
                            <tr>
                                <td>{{ $fournisseur->for_nom }}</td>
                                <td>{{ $fournisseur->for_ville }}</td>
                                <td>{{ $fournisseur->for_email }}</td>
                                <td>{{ $fournisseur->for_telephone }}</td>
                                <td><a class="btn" href="{{ route('fournisseurs.show',$fournisseur->id) }}"><i class="fa fa-eye" style="color: #000000;"></i></a></td>
                                <td><a class="btn" href="{{ route('fournisseurs.edit',$fournisseur->id) }}"><i class="fa fa-edit" style="color: #000000;"></i></a></td>
                                <td>
                                    <form action="{{ route('fournisseurs.destroy',$fournisseur->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn" type="submit"><i class="fa fa-trash" style="color: #000000;"></i></button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="d-flex justify-content-center">
                {!! $fournisseurs->links('pagination::bootstrap-4') !!}
            </div>
        </div>
    </div>
@endsection

resources/views/fournisseurs/show.blade.php
@extends('layouts.userApp')

@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="card">
                <div class="header">
                    <a class="btn btn-info btn-fill" href="{{ route('fournisseurs.index') }}">Retour</a>
                    <a class="btn btn-info btn-fill" href="{{ route('fournisseurs.edit', $fournisseur->id) }}">Modifer</a>
                </div>
                <div class="content">
                    <form>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>{{ __('Nom Complet') }}</label>
                                    <input type="" class="form-control" value="{{ $fournisseur->for_nom }}" readonly>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label>{{ __('E-mail') }}</label>
                                    <input type="text" class="form-control" value="{{ $fournisseur->for_email }}" readonly>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>{{ __('RIB') }}</label>
                                    <input type="text" class="form-control" name="rib" value="{{ $fournisseur->rib }}" readonly>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>{{ __('N° Telephone') }}</label>
                                    <input class="form-control" value="{{ $fournisseur->for_telephone }}" readonly>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>{{ __('Fax') }}</label>
                                    <input class="form-control" value="{{ $fournisseur->for_fax }}" readonly>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <div class="form-group">
                                    <label>{{ __('Ville') }}</label>
                                    <input class="form-control" value="{{ $fournisseur->for_ville }}" readonly>
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="form-group">
                                    <label>{{ __('Code Postale') }}</label>
                                    <input class="form-control" value="{{ $fournisseur->for_zip }}" readonly>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label>{{ __('Adresse') }}</label>
                                    <input type="" class="form-control" value="{{ $fournisseur->for_adress }}" readonly>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>{{ __('La date d\'ajout') }}</label>
                                    <input class="form-control" value="{{ $fournisseur->created_at }}" readonly>
                                </div>
                            </div>
                            @if($fournisseur->updated_at != $fournisseur->created_at)
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>{{ __('Mis a jour') }}</label>
                                    <input class="form-control" value="{{ $fournisseur->updated_at }}" readonly>
                                </div>
                            </div>
                            @endif
                        </div>
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    @if(Auth::user()->is_admin)
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="row center-block">
                <div class="col-md-6">
                    <div class="card">
                        <div class="header">
                            <button class="btn btn-info btn-fill center-block">{{ __('Liste des materiels fournit par ').$fournisseur->for_nom }}</button>
                        </div>
                        <br/>
                        <div class="content table-responsive table-full-width">
                            <table class="table table-hover table-striped">
                                <thead>
                                <th>{{__('Serie')}}</th>
                                <th>{{__('Name')}}</th>
                                <th>{{__('Plus')}}</th>
                                </thead>
                                <tbody>
                                @foreach ($materiels as $materiel)
                                    <tr>
                                        <td>{{ $materiel->mat_serie }}</td>
                                        <td>{{ $materiel->mat_nom }}</td>
                                        <td> <a class="btn" href="{{ route('materiels.show',$materiel->id) }}"><i class="fa fa-eye" style="color: #000000;"></i></a></td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card">
                        <div class="header">
                            <button class="btn btn-info btn-fill center-block">{{ __('Liste des logiciels fournit par ').$fournisseur->for_nom }}</button>
                        </div>
                        <br/>
                        <div class="content table-responsive table-full-width">
                            <table class="table table-hover table-striped">
                                <thead class="thead-dark">
                                <th>{{__('Serie')}}</th>
                                <th>{{__('Name')}}</th>
                                <th>{{__('Plus')}}</th>
                                </thead>
                                <tbody>
                                @foreach ($logiciels as $logiciel)
                                    <tr>
                                        <td>{{ $logiciel->log_serie }}</td>
                                        <td>{{ $logiciel->log_nom }}</td>
                                        <td> <a class="btn" href="{{ route('logiciels.show',$logiciel->id) }}"><i class="fa fa-eye" style="color: #000000;"></i></a></td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endif
@endsection